### PR TITLE
new_timestamp

### PR DESCRIPTION
**Pull request by optinsoft**
I've added new_timestamp method that can be used before repackage to set new timestamp, like this:

```python
new_timestamp: int = fp.new_timestamp()
new_bda = fp.repackage()
```

### CODE REVIEW

**Comment by spearphishing** [comment]
Instead of a whole separate `.new_timestamp` function, why not add timestamp as a kwarg to `.repackage`?

### Example Function Call

```py
repackaged = fp.repackage(timestamp = ...)
```

 Also as a replacement to the `.new_timestamp`'s functionality of generating a new interval timestamp you could have a static method called `generate_current_arkose_timestamp`

### Final Snippet

```py
repackaged = fp.repackage(timestamp = ...)
```

**Comment by spearphishing** [comment]
Instead of a whole separate `.new_timestamp` function, why not add timestamp as a kwarg to `.repackage`?

### Example Function Call

```py
repackaged = fp.repackage(timestamp = ...)
```

 Also, as a replacement to the `.new_timestamp`'s functionality of generating a new interval timestamp you could have a static method called `generate_current_arkose_timestamp`

### Example Implementation

```py
from unfuncaptcha_bda import ArkoseBrowserFingerprint

bda="eyJjdCI6ImlvMmJUS3lrSnFObEdEU..."
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0"
fp = ArkoseBrowserFingerprint(bda, user_agent)

repackaged = fp.repackage(
    timestamp = ArkoseBrowserFingerprint.generate_current_arkose_timestamp()
)
```

**Comment by optinsoft** [comment]
I've added new function instead of `timestamp` kwarg to preserve compatibility. `repackage` does not change the state of `ArkoseBrowserFingerprint`. Repackage uses old `self._key` (`self.crypto`). But if add `timestamp` arg to `repackage` then `self._key` and `self.crypto` will be new. And that may break backward compatibility if somebody uses `repackage`.

**Comment by spearphishing** [comment]
You're right, sorry for the oversight. Other than some minor nitpicks I had in the code, LGTM.

**Pull request merged**
